services:
  keria:
    image: ${BANK_KERIA_IMAGE}
    environment:
      - KERI_AGENT_CORS=1
      - KERI_URL=http://keria:3902
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
    volumes:
      - ./config/testkeria.json:/keria/config/keri/cf/keria.json
    entrypoint:
      [
        "keria",
        "start",
        "--config-dir",
        "/keria/config",
        "--config-file",
        "keria",
        "--name",
        "agent",
      ]
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://keria:3902/spec.yaml"]
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
    ports:
      - 3901:3901
      - 3902:3902
      - 3903:3903

  verify:
    image: alpine
    command: ["echo", "Dependencies running"]
    depends_on:
      keria:
        condition: service_healthy
