services:
  reg-webapp:
    image: 2byrds/reg-webapp:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 8s
    ports:
      - 3000:3000

  vlei-server:
    image: gleif/vlei
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
    command:
      - vLEI-server
      - -s
      - ./schema/acdc
      - -c
      - ./samples/acdc/
      - -o
      - ./samples/oobis/
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:7723/oobi/EBfdlu8R27Fbx-ehrqwImnK-8Cm79sqbAQ4MmvEAYqao
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
    ports:
      - 7723:7723

  keria:
    image: ${KERIA_IMAGE:-weboftrust/keria}:${KERIA_IMAGE_TAG:-latest}
    environment:
      - KERI_AGENT_CORS=1
      - KERI_URL=http://keria:3902
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
    volumes:
      - ./config/keria.json:/keria/config/keri/cf/keria.json
    entrypoint:
      [
        "keria",
        "start",
        "--config-dir",
        "/keria/config",
        "--config-file",
        "keria",
        "--name",
        "agent",
      ]
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://keria:3902/spec.yaml"]
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
    ports:
      - 3901:3901
      - 3902:3902
      - 3903:3903

  witness-demo:
    image: weboftrust/keri-witness-demo:1.1.0
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5642/oobi"]
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
    volumes:
      - ./config/witness-demo:/keripy/scripts/keri/cf/main
    ports:
      - 5642:5642
      - 5643:5643
      - 5644:5644

  reg-pilot-api:
    image: gleif/reg-pilot-api:latest
    ports:
      - 8000:8000
    environment:
      - ENABLE_CORS=true
      - VLEI_VERIFIER=http://vlei-verifier:7676
      - FILER_REPORTS=http://reg-pilot-filer:7878/reports/
      - FILER_ADMIN_UPLOAD_STATUSES=http://reg-pilot-filer:7878/admin/upload_statuses/
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://reg-pilot-api:8000/ping"]
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s

  vlei-verifier:
    image: gleif/vlei-verifier:latest
    container_name: vlei-verifier
    hostname: vlei-verifier
    environment:
      - VERIFIER_CONFIG_FILE=verifier-config-test.json
    depends_on:
      - vlei-server
      - witness-demo
    ports:
      - 7676:7676
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://vlei-verifier:7676/health"]
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s

  reg-pilot-filer:
    image: gleif/reg-pilot-filer:latest
    container_name: reg-pilot-filer
    hostname: reg-pilot-filer
    ports:
      - 7878:7878
    environment:
      - VLEI_VERIFIER=http://vlei-verifier:7676
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://reg-pilot-filer:7878/health"]
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s

  proxy-server:
    build:
      context: ../proxy-server
      dockerfile: Dockerfile
    ports:
      - 3434:3434
    depends_on:
      - reg-pilot-api
    healthcheck:
      test: ["CMD", "wget", "http://proxy-server:3434/ping"]
      interval: 2s
      timeout: 3s
      retries: 5

  deps:
    image: alpine
    command: ["echo", "Dependencies running"]
    depends_on:
      vlei-server:
        condition: service_healthy
      keria:
        condition: service_healthy
      witness-demo:
        condition: service_healthy

  verify:
    image: alpine
    command: ["echo", "Dependencies running"]
    depends_on:
      keria:
        condition: service_healthy
      reg-pilot-api:
        condition: service_healthy
      vlei-verifier:
        condition: service_healthy
      reg-pilot-filer:
        condition: service_healthy

  proxy-verify:
    image: alpine
    command: ["echo", "Dependencies running"]
    depends_on:
      keria:
        condition: service_healthy
      proxy-server:
        condition: service_healthy
      reg-pilot-api:
        condition: service_healthy
      vlei-verifier:
        condition: service_healthy
      reg-pilot-filer:
        condition: service_healthy
